### ISSUE TITLE
Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by wnabil** [Hydrane/angular2-notification-bar#4]
Hello 
Thank you for this awesome module.
When i build the project as a production with the angular cli i got this error message :
`ERROR in ./~/angular2-notification-bar/src/notification-bar.service.ts
Module build failed: TypeError: Cannot read property 'text' of undefined
    at Object.getTokenPosOfNode (/home/orange/Desktop/projects/maker/maker-front/node_modules/typescript/lib/typescript.js:5692:71)
    at IdentifierObject.TokenOrIdentifierObject.getStart (/home/orange/Desktop/projects/maker/maker-front/node_modules/typescript/lib/typescript.js:53623:23)
    at IdentifierObject.TokenOrIdentifierObject.getText (/home/orange/Desktop/projects/maker/maker-front/node_modules/typescript/lib/typescript.js:53644:77)
    at refactor.findAstNodes.filter (/home/orange/Desktop/projects/maker/maker-front/node_modules/@ngtools/webpack/src/loader.js:138:44)
    at Array.filter (native)
    at refactor.findAstNodes.forEach.node (/home/orange/Desktop/projects/maker/maker-front/node_modules/@ngtools/webpack/src/loader.js:137:14)
    at Array.forEach (native)
    at _removeDecorators (/home/orange/Desktop/projects/maker/maker-front/node_modules/@ngtools/webpack/src/loader.js:128:10)
    at Promise.resolve.then (/home/orange/Desktop/projects/maker/maker-front/node_modules/@ngtools/webpack/src/loader.js:304:33)
@ ./~/angular2-notification-bar/index.ts 2:0-47
 @ ./src/app/auth0/auth.service.ts
 @ ./src/$$_gendir/app/app.module.ngfactory.ts
 @ ./src/main.ts
 @ multi ./src/main.ts`
version :1.2.3
angular version :2.3.1
cli version : 1.0.0-beta.32.3

**Comment by jsrkstr** [comment]
Hi, I am quite busy with something at the moment. If you can create a pull request with fix I can merge it and update. Thanks.

**Comment by wnabil** [comment]
Ok i will but maybe it will take some time because i am new to typescript
Also i don't have permissions

**Comment by jsrkstr** [comment]
Hi, you don't need permissions to contribute to this project. You can simply follow these steps - 
1. Fork this repository
2. Clone this repo in your computer
3. Fix bug and commit
4. Create pull request to original repo

After you make a pull request, I will accept and your changes will be done in original repo.

Thanks!

**Comment by wnabil** [comment]
Hello @jsrockstar132
i found that the problem is the module include the ts files
the angular CLI compiler will fail if you build the project as a production or AOT.
to fix this issue i have to delete the ts files which are in the /src folder and the index.ts file and re-point the module in my project to the /release/index.d.ts file
everything works fine after that.
Thanks
